spring:
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
    clear-checksums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8080
