server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    template:
      default-topic: topic1


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
#    clear-checksums: true


  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect





